TITLE = "The Flag Game"
START_MASSAGE = "Welcome to The Flag game. Have Fun!"
START_LOCATION = (0,0)
MINE = "MINE"
NO_MINE = "EMPTY"

SOLIDER_STEP = 20

SOLIDER_WIDTH = 40
SOLIDER_HEIGHT = 80
SOLDIER_SIZE = (SOLIDER_WIDTH,SOLIDER_HEIGHT)

FLAG_WIDTH = 80
FLAG_HEIGHT = 60
FLAG_SIZE = (FLAG_WIDTH,FLAG_HEIGHT)

MINE_WIDTH = 60
MINE_HEIGHT = 20
MINE_SIZE = (MINE_WIDTH,MINE_HEIGHT)

ROW = 25
COL = 50

WINDOW_HEIGHT = 500
WINDOW_WIDTH = 1000

GREEN = (159,226,191)
BLACK = (0,0,0)

MOVE_LEFT = "left"
MOVE_RIGHT = "right"
MOVE_UP = "up"
MOVE_DOWN = "down"

EXPLOTION_IMG = "explotion.png"
FLAG_IMG = "flag.png"
GRASS_IMG = "grass.png"
INJURY_IMG = "injury.png"
MINE_IMG = "mine.png"
SNAKE_IMG = "snake.png"
SOLIDER_IMG = "soldier.png"
SOLIDER_2_IMG = "solider_2.png"
SOLIDER_NIGHT = "solider_night.png"

FLAG_LOCATION = (WINDOW_WIDTH,WINDOW_HEIGHT)


